[package]
name = "blog_os"
version = "0.1.0"
authors = ["Yamashita <jey.togo@gmail.com>"]
edition = "2018"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[unstable]
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-blog_os.json"
